pipeline:
  build:
    image: golang:1.8
    environment:
      - GOPATH=/drone
    commands:
      - go test ./pkg/...
      - CGO_ENABLED=0 go build -o bin/sqs-autoscaler-controller main.go

  docker-push:
    when:
      event: push
    image: plugins/docker
    registry: quay.io
    repo: quay.io/uswitch/sqs-autoscaler-controller
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_SHA:0:8}
